### ISSUE TITLE
Blocking?

### ISSUE THREAD

**Issue by viktor1970** [Roman3349/MCP980X-arduino#2]
Hallo, I experienced if the sensor (MCP9802 in my case) is disconnected the read method starts an infinite loop.
Removing the "while (Wire.available() < lenght) {	}" it works perfectly.

Regards

Vittorio

**Comment by Koepel** [comment]
There is no need to wait for something after the Wire.requestFrom(). That while-loop should be removed.

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. There is no need to wait for something to read data from that buffer.

If the sensor is disconnected, the Wire.available() would probably return zero, and that while-loop would halt the sketch. Since that while-loop is not okay anyway, it is better to remove it.

**Comment by Roman3349** [comment]
@viktor1970 @Koepel Thank you.
